[package]
name = "tunnelblickctl"
version = "0.1.0"
authors = ["Ben Webber"]

[dependencies]
csv = "1.1"
humansize = "~1.1.0"
osascript = "~0.3.0"
serde = "~1.0.0"
serde_derive = "~1.0.0"
serde_json = "~1.0.0"
tabwriter = "~1.1.0"

[dependencies.clap]
features = ["yaml"]
version = "~2.19.0"
